data = ["Ngày uống 2 lần, mỗi lần 2 viên (sáng), trong 2 ngày.",
        "Uống mỗi ngày 2 lần, mỗi lần 2 viên (uống sau ăn), trong 2 ngày.",
        "Mỗi ngày uống 1 lần, mỗi lần 1 viên (uống trước ăn), trong 5 ngày.",
        "Uống 3 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 7 ngày.",
        "Mỗi ngày uống 2 lần, mỗi lần 1 viên (uống trước ăn), trong 10 ngày.",
        "Uống 1 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 3 ngày.",
        "Mỗi ngày uống 2 lần, mỗi lần 1 viên (uống trước ăn), trong 14 ngày.",
        "Uống 2 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 21 ngày.",
        "Mỗi ngày uống 1 lần, mỗi lần 1 viên (uống trước ăn), trong 30 ngày.",
        "Uống 3 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 15 ngày.",
        "Mỗi ngày uống 2 lần, mỗi lần 1 viên (uống trước ăn), trong 28 ngày.",
        "Uống 1 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 12 ngày.",
        "Mỗi ngày uống 2 lần, mỗi lần 1 viên (uống trước ăn), trong 18 ngày.",
        "Uống 2 lần mỗi ngày, mỗi lần 1 viên (uống sau ăn), trong 25 ngày."]